Traceback (most recent call last):
  File "/data/home/wgy/workspace/bin/gellmo/GeLLMO/inference.py", line 170, in <module>
    fire.Fire(main)
  File "/data/home/wgy/workspace/local/anaconda3/envs/gellmo/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/wgy/workspace/local/anaconda3/envs/gellmo/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/data/home/wgy/workspace/local/anaconda3/envs/gellmo/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/wgy/workspace/bin/gellmo/GeLLMO/inference.py", line 43, in main
    test_data = load_dataset(data_path)['test']
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/wgy/workspace/local/anaconda3/envs/gellmo/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/wgy/workspace/local/anaconda3/envs/gellmo/lib/python3.11/site-packages/datasets/load.py", line 1853, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/wgy/workspace/local/anaconda3/envs/gellmo/lib/python3.11/site-packages/datasets/load.py", line 1729, in dataset_module_factory
    raise e1 from None
  File "/data/home/wgy/workspace/local/anaconda3/envs/gellmo/lib/python3.11/site-packages/datasets/load.py", line 1616, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({e.__class__.__name__})") from e
ConnectionError: Couldn't reach 'NingLab/MuMOInstruct' on the Hub (LocalEntryNotFoundError)
srun: error: localhost: task 0: Exited with exit code 1
